In [1]:

# http://janmatuschek.de/LatitudeLongitudeBoundingCoordinates
# dist = arccos(sin(lat1) · sin(lat2) + cos(lat1) · cos(lat2) · cos(lon1 - lon2)) · R
import math
# xlimit_high_long= -8.62000
# xlimit_low_long= -8.64000
# ylimit_high_lat= 41.16
# ylimit_low_lat= 41.1450
# Radius of the world
# R=
xlimit_high_long= 116.400
xlimit_low_long= 116.350
ylimit_high_lat= 40.100
ylimit_low_lat= 40.050

# xlimit_high_long= 116.400
# xlimit_low_long= 116.320
# ylimit_high_lat= 40.100
# ylimit_low_lat= 40.020


# max_latitude1=40.100
# min_latitude1=39.900
# max_longitude1=116.500
# min_longitude1=116.300
area=math.acos(math.sin(ylimit_high_lat)*math.sin(ylimit_low_lat)+
               math.cos(ylimit_high_lat)*math.cos(ylimit_low_lat)*math.cos(xlimit_high_long-xlimit_low_long))*6371

print(area)


392.63507514506205


In [2]:
# lon_high= -8.62000
# lon_low= -8.64000
# lat_high= 41.16
# lat_low= 41.1450

lon_high= 116.400
lon_low= 116.350
lat_high= 40.100
lat_low= 40.050

# lon_high= 116.400
# lon_low= 116.320
# lat_high= 40.100
# lat_low= 40.020
# we will divide this area into 11(lat)*14(lon) grid
lon_difference=abs(lon_high-lon_low)
lon_fraction=lon_difference/14
lat_difference=abs(lat_high-lat_low)
lat_fraction=lat_difference/11
print(lon_fraction)
print(lat_fraction)

0.0035714285714293836
0.004545454545454933


In [3]:
lon_axis=[]
lon_axis.append(lon_low)
for i in range(13):
    temp=lon_axis[i]+lon_fraction
    lon_axis.append(temp)
lon_axis.append(lon_high)
print(lon_axis)
    

[116.35, 116.35357142857143, 116.35714285714286, 116.3607142857143, 116.36428571428573, 116.36785714285716, 116.3714285714286, 116.37500000000003, 116.37857142857146, 116.3821428571429, 116.38571428571433, 116.38928571428576, 116.3928571428572, 116.39642857142863, 116.4]


In [4]:
lat_axis=[]
lat_axis.append(lat_low)
for i in range(10):
    temp=lat_axis[i]+lat_fraction
    lat_axis.append(temp)
lat_axis.append(lat_high)
print(lat_axis)

[40.05, 40.054545454545455, 40.05909090909091, 40.06363636363637, 40.06818181818183, 40.072727272727285, 40.07727272727274, 40.0818181818182, 40.08636363636366, 40.090909090909115, 40.09545454545457, 40.1]


In [5]:
lon_axis[5]

116.36785714285716

In [6]:
import pandas as pd
import numpy as np
import os

In [7]:
# heat_array = np.zeros((11, 14),dtype=int)
# print(heat_array)
allfiles=os.listdir('original')
if '.ipynb_checkpoints' in allfiles:
    allfiles.remove('.ipynb_checkpoints')
len(allfiles)
# for i in range(10):
#     filename="original/"+allfiles[i]
#     i=i+1
#     rawData = pd.read_csv(filename)
#     for data in range(len(rawData)):
#         Rawtrajectories=Rawtrajectories+1
#         lat=rawData.latitude[data]
#         lon=rawData.longitude[data]
#         lon_column=None
#         lat_row=None
#         for ln in range(len(lon_axis)-1):
#             ln_1=ln+1
#             if lon>=lon_axis[ln] and lon<lon_axis[ln_1]:
#                 lon_column=ln
#                 break
#         for lt in range(len(lat_axis)-1):
#             lt_1=lt+1
#             if lat>=lat_axis[lt] and lat<lat_axis[lt_1]:
#                 lat_row=lt
#                 break
#         heat_array[lat_row,lon_column]=heat_array[lat_row,lon_column]+1
        
# print(heat_array)
                

10656

In [8]:
import pandas as pd
import numpy as np
heat_array = np.zeros((11, 14),dtype=int)
print(heat_array)
Rawtrajectories=0
for i in range(10656):
    filename="original/"+allfiles[i]
#     i=i+1
#     filename="raw_data/rawData_"+str(i)+".csv"
#     filename="rawData/rawData_"+str(i)+".csv"
    
#     print(filename)
    rawData = pd.read_csv(filename)
#     print(rawData)
    
    for data in range(len(rawData)):
        
        lat=rawData.latitude[data]
        lon=rawData.longitude[data]
#         lat=rawData.lat[data]
#         lon=rawData.lon[data]
#         print(lat)
#         print(lon)
        lon_column=None
        lat_row=None
        for ln in range(len(lon_axis)-1):
            ln_1=ln+1
            if lon>=lon_axis[ln] and lon<lon_axis[ln_1]:
#                 print(lon_axis[ln])
#                 print(lon_axis[ln_1])
                lon_column=ln 
                break
#         print(lon_column)
        for lt in range(len(lat_axis)-1):
            lt_1=lt+1
            if lat>=lat_axis[lt] and lat<lat_axis[lt_1]:
#                 print(lat_axis[lt])
#                 print(lat_axis[lt_1])
                lat_row=lt
                break
        if(lat_row!=None and lon_column!=None ):
            Rawtrajectories=Rawtrajectories+1
            heat_array[lat_row,lon_column]=heat_array[lat_row,lon_column]+1
print(heat_array)
        

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


PermissionError: [Errno 13] Permission denied: 'original/v1'

In [ ]:
print(Rawtrajectories)

In [ ]:
allfiles=os.listdir('staticMap')
if '.ipynb_checkpoints' in allfiles:
    allfiles.remove('.ipynb_checkpoints')
len(allfiles)

In [ ]:
# Rawtrajectories=50000000
syntheticTrajectories=0
heat_array_traj = np.zeros((11, 14),dtype=int)
print(heat_array_traj)
for i in range(10655):
    filename="staticMap/"+allfiles[i]

    rawData = pd.read_csv(filename)
    for data in range(len(rawData)):
        if(syntheticTrajectories==Rawtrajectories):
            break
        else:
            
            lat=rawData.latitude[data]
            lon=rawData.longitude[data]
            lon_column=None
            lat_row=None
            for ln in range(len(lon_axis)-1):
                ln_1=ln+1
                if lon>=lon_axis[ln] and lon<lon_axis[ln_1]:
                    lon_column=ln
                    break
            for lt in range(len(lat_axis)-1):
                lt_1=lt+1
                if lat>=lat_axis[lt] and lat<lat_axis[lt_1]:
                    lat_row=lt
                    break
            if(lat_row!=None and lon_column!=None ):
                syntheticTrajectories=syntheticTrajectories+1
                heat_array_traj[lat_row,lon_column]=heat_array_traj[lat_row,lon_column]+1
print(heat_array_traj)

In [ ]:
allfiles=os.listdir('osmnx')
if '.ipynb_checkpoints' in allfiles:
    allfiles.remove('.ipynb_checkpoints')
len(allfiles)

In [ ]:
# Rawtrajectories=50000000
syntheticTrajectories_osmnx=0
heat_array_traj_osmnx = np.zeros((11, 14),dtype=int)
print(heat_array_traj_osmnx)
for i in range(10655):
    filename="osmnx/"+allfiles[i]

    rawData = pd.read_csv(filename)
    for data in range(len(rawData)):
        if(syntheticTrajectories==Rawtrajectories):
            break
        else:
            
            lat=rawData.latitude[data]
            lon=rawData.longitude[data]
            lon_column=None
            lat_row=None
            for ln in range(len(lon_axis)-1):
                ln_1=ln+1
                if lon>=lon_axis[ln] and lon<lon_axis[ln_1]:
                    lon_column=ln
                    break
            for lt in range(len(lat_axis)-1):
                lt_1=lt+1
                if lat>=lat_axis[lt] and lat<lat_axis[lt_1]:
                    lat_row=lt
                    break
            if(lat_row!=None and lon_column!=None ):
                syntheticTrajectories_osmnx=syntheticTrajectories_osmnx+1
                heat_array_traj_osmnx[lat_row,lon_column]=heat_array_traj_osmnx[lat_row,lon_column]+1
print(heat_array_traj_osmnx)

In [ ]:
print(syntheticTrajectories_osmnx)

In [ ]:
from scipy.spatial import distance

In [ ]:
from numpy.linalg import norm
Aflat = np.hstack(heat_array)
Bflat = np.hstack(heat_array_traj)

dist = distance.cosine(Aflat, Bflat)
print("Cosine Distance :" ,dist)
cosine = np.dot(Aflat,Bflat)/(norm(Aflat)*norm(Bflat))
print("Cosine Similarity:", cosine)

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# np.random.seed(0)
# A = np.random.uniform(0,500,(4,3))
sns.heatmap(heat_array_traj, square=True)
# plt.xlim(lon_low, lon_high)
# plt.ylim(lat_low, lat_high)
plt.show()

In [ ]:
sns.heatmap(heat_array, square=True)
plt.show()

In [ ]:
# Raw and OSMNX
from numpy.linalg import norm
Aflat = np.hstack(heat_array)
Bflat = np.hstack(heat_array_traj_osmnx)

dist = distance.cosine(Aflat, Bflat)
print("Cosine Distance :" ,dist)
cosine = np.dot(Aflat,Bflat)/(norm(Aflat)*norm(Bflat))
print("Cosine Similarity:", cosine)

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# np.random.seed(0)
# A = np.random.uniform(0,500,(4,3))
sns.heatmap(heat_array_traj_osmnx, square=True)
# plt.xlim(lon_low, lon_high)
# plt.ylim(lat_low, lat_high)
plt.show()

In [ ]:
# # Rawtrajectories=50000000
# syntheticTrajectories=0
# heat_array_traj = np.zeros((11, 14),dtype=int)
# print(heat_array_traj)
# for i in range(10655):
#     filename="staticMap/"+allfiles[i]
# #     i=i+1
# #     filename="syntheticTrajectories/syntheticTrajectories"+str(i)+".csv"
# #     filename="raw_data/rawData_"+str(i)+".csv"
# #     print(filename)
#     rawData = pd.read_csv(filename)
# #     print(rawData)
#     for data in range(len(rawData)):
#         if(syntheticTrajectories==Rawtrajectories):
# #             print(filename)
#             break
#         else:
#             syntheticTrajectories=syntheticTrajectories+1
#     #     for data in range(1):
#             lat=rawData.lat[data]
#             lon=rawData.lon[data]
#     #         print(lat)
#     #         print(lon)
#             lon_column=None
#             lat_row=None
#             for ln in range(len(lon_axis)-1):
#                 ln_1=ln+1
#                 if lon>=lon_axis[ln] and lon<lon_axis[ln_1]:
#     #                 print(lon_axis[ln])
#     #                 print(lon_axis[ln_1])
#                     lon_column=ln
#                     break
#     #         print(lon_column)
#             for lt in range(len(lat_axis)-1):
#                 lt_1=lt+1
#                 if lat>=lat_axis[lt] and lat<lat_axis[lt_1]:
#     #                 print(lat_axis[lt])
#     #                 print(lat_axis[lt_1])
#                     lat_row=lt
#                     break
#     #         print(lat_row)
#             heat_array_traj[lat_row,lon_column]=heat_array_traj[lat_row,lon_column]+1
# print(heat_array_traj)